version: "3"

services:
  namenode:
    build:
      context: ./namenode
      dockerfile: Dockerfile
    image: hadoop-namenode
    container_name: namenode
    restart: no
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    build:
      context: ./datanode
      dockerfile: Dockerfile
    image: hadoop-datanode
    container_name: datanode
    restart: no
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  datanode2:
    build:
      context: ./datanode
      dockerfile: Dockerfile
    image: hadoop-datanode
    container_name: datanode2
    restart: no
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    build:
      context: ./resourcemanager
      dockerfile: Dockerfile
    image: hadoop-resourcemanager
    container_name: resourcemanager
    restart: no
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    build:
      context: ./nodemanager
      dockerfile: Dockerfile
    image: hadoop-nodemanager
    container_name: nodemanager
    restart: no
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    build:
      context: ./historyserver
      dockerfile: Dockerfile
    image: hadoop-historyserver
    container_name: historyserver
    restart: no
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode2:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_datanode2:
  hadoop_historyserver:
